package com.projecta.monsai.sql;

import java.util.HashSet;

/**
 * The SqlRewriter knows the types of queries generated by Mondrian, and tries
 * to fix some known problems:
 *
 * - When using sum() or count(distinct) on a field of type hll, the aggregation
 *   is replaced by a call to hll_cardinality()
 *
 * - When using a constraint on a joined dimension table, the fact table will be
 *   constraint as well, to help the postgres execution planner
 *
 * @author akuehnel
 */
public class SqlRewriterTest {

    public static void main( String[] args ) {

        SqlRewriter sqlRewriter = new SqlRewriter();

        SqlRewriter.hyperLogLogColumnsCache = new HashSet<>();
        SqlRewriter.hyperLogLogColumnsCache.add( "m_dim.touchpoints_fact.visitors" );

        String sql = sqlRewriter.rewrite(
            "select\n" +
            "    \"day\".\"month_id\" as \"c0\",\n" +
            "    \"performance_attribution_model\".\"performance_attribution_model_id\" as \"c1\",\n" +
            "    \"region\".\"country_id\" as \"c2\",\n" +
            "    sum(\"touchpoints_fact\".\"visitors\") as \"m0\",\n" +
            "    sum(\"touchpoints_fact\".\"number_of_first_net_orders\") as \"m1\",\n" +
            "    sum(\"touchpoints_fact\".\"number_of_recurring_net_orders\") as \"m2\"\n" +
            "from\n" +
            "    \"os_dim\".\"day\" as \"day\",\n" +
            "    \"m_dim\".\"touchpoints_fact\" as \"touchpoints_fact\",\n" +
            "    \"m_dim\".\"performance_attribution_model\" as \"performance_attribution_model\",\n" +
            "    \"m_dim\".\"region\" as \"region\"\n" +
            "where ...", null );
        System.out.println( sql );

        String sql2 = sqlRewriter.rewrite(
                "select\n" +
                "    \"acquisition_channel\".\"acquisition_type_id\" as \"c0\",\n" +
                "    \"acquisition_channel\".\"acquisition_type_name\" as \"c1\",\n" +
                "    \"acquisition_channel\".\"acquisition_category_id\" as \"c2\",\n" +
                "    \"acquisition_channel\".\"acquisition_category_name\" as \"c3\"\n" +
                "from\n" +
                "    \"os_dim\".\"acquisition_channel\" as \"acquisition_channel\",\n" +
                "    \"os_dim\".\"revenue_planning\" as \"revenue_planning\",\n" +
                "    \"os_dim\".\"day\" as \"day\"\n" +
                "where\n" +
                "    \"revenue_planning\".\"acquisition_channel_fk\" = \"acquisition_channel\".\"acquisition_channel_id\"\n" +
                "and\n" +
                "    \"revenue_planning\".\"invoice_day_fk\" = \"day\".\"day_id\"\n" +
                "and\n" +
                "    \"day\".\"day_type_id\" = 1\n" +
                "and\n" +
                "    (\"acquisition_channel\".\"acquisition_type_id\" in (1, 2, 3, 4))\n" +
                "group by\n" +
                "    \"acquisition_channel\".\"acquisition_type_id\",\n" +
                "    \"acquisition_channel\".\"acquisition_type_name\",\n" +
                "    \"acquisition_channel\".\"acquisition_category_id\",\n" +
                "    \"acquisition_channel\".\"acquisition_category_name\"\n" +
                "order by\n" +
                "    \"acquisition_channel\".\"acquisition_type_id\" ASC NULLS LAST,\n" +
                "    \"acquisition_channel\".\"acquisition_category_id\" ASC NULLS LAST", null );

        System.out.println( sql2 );
    }

}

